
#ifndef GEOGRAM_BASIC_VERSION
#define GEOGRAM_BASIC_VERSION

#define VORPALINE_VERSION_MAJOR "1"
#define VORPALINE_VERSION_MINOR "9"
#define VORPALINE_VERSION_PATCH "1"
#define VORPALINE_VERSION "1.9.1-rc"
#define VORPALINE_BUILD_NUMBER ""
#define VORPALINE_BUILD_DATE "2024-08-22 21:40:43"
#define VORPALINE_SVN_REVISION ""

#endif